.\" Copyright Petr Hracek, 2017
.\"
.\" This page is distributed under GPL.
.\"
.TH mtf-env-clean 1 2017-11-01 "" "Linux User's Manual"
.SH NAME
mtf-env-set \- Part of Meta-Test-Family package. It cleans environment for testing containers.

.SH SYNOPSIS
\fBmtf-env-clean cleans environment for testing containers

.SH DESCRIPTION
\fBmtf-env-clean\fP is the binary file for cleaning environment of Meta-Test-Family. It stops docker service.

.SH NOTES
\fBmtf-env-clean\fP is useful for users who don't want to care about environment and their clean up.

.SH AUTHORS
Petr Hracek, <phracek@redhat.com> (man page)
