.\" Copyright Petr Hracek, 2017
.\"
.\" This page is distributed under GPL.
.\"
.TH MTF-ENV-SET 1 2017-11-01 "" "Linux User's Manual"
.SH NAME
mtf-env-set \- prepares environment for testing containers.

.SH SYNOPSIS
.B mtf-env-set

.SH DESCRIPTION
.PP
\fBmtf-env-clean\fP  is the binary file of Meta-Test-Family package. It installs tests dependencies, docker service
and starts docker service.

.SH NOTES
\fBmtf-env-set\fP mtf-env-set is useful for people who don't want to set the environment manually
and wish to use this executable to do the job.

.SH AUTHORS
Petr Hracek, <phracek@redhat.com> (man page)

.SH "SEE ALSO"
Full documentation at: <http://meta-test-family.readthedocs.io/en/latest/user_guide/environment_setup.html>