.\" Copyright Petr Hracek, 2017
.\"
.\" This page is distributed under GPL.
.\"
.TH mtf-env-set 1 2017-11-01 "" "Linux User's Manual"
.SH NAME
mtf-env-set \- Part of Meta-Test-Family package. It prepares environment for testing containers.

.SH SYNOPSIS
\fBmtf-env-set prepares environment for testing containers

.SH DESCRIPTION
\fBmtf-env-set\fP is the binary file of Meta-Test-Family. It installs tests dependencies, docker service
 and starts docker service.

.SH NOTES
\fBmtf-env-set\fP is useful for users who don't want to care about environment and their settings.

.SH AUTHORS
Petr Hracek, <phracek@redhat.com> (man page)
