.TH mtf-generator "1" Manual
.SH NAME
mtf-generator \- Its is a binary file included in Meta-Test-Family package.  It generates code for tests written in config.yaml file for usage by mtf binary.
.SH SYNOPSIS
.B mtf-generator
[-h]
.SH DESCRIPTION
generates code for tests written in config.yaml file.

.SH AUTHORS
.B meta\-test\-family
was written by Jan Scotka <jscotka@redhat.com>.
.SH DISTRIBUTION
The latest version of meta\-test\-family may be downloaded from
.UR https://github.com/fedora\-modularity/meta\-test\-family
.UE
