.\" Copyright Petr Hracek, 2017
.\"
.\" This page is distributed under GPL.
.\"
.TH mtf-generator 1 2017-11-01 "" "Linux User's Manual"
.SH NAME
mtf-generator \- generates tests written in \fBconfig.yaml\fP file.

.SH SYNOPSIS
.B
mtf

.SH DESCRIPTION
\fBmtf-generator\fP is the binary file of Meta-Test-Family package.
It generates tests written \fBconfig.yaml\fP file for using by \fBmtf\fP binary.

.SH AUTHORS
Petr Hracek, <phracek@redhat.com> (man page)

