.TH mtf "1" Manual
.SH NAME
mtf \- tool to test components for a modular Fedora.
.SH SYNOPSIS
.B mtf
[options] local_tests
.SH DESCRIPTION
unknown arguments are forwarded to avocado:
.br
   optionally use additional avocado param like \-\-show\-job\-log, see avocado action \-\-help
.SH OPTIONS

.TP
\fB\-\-linter\fR, \fB\-l\fR
adds additional compose checks

.TP
\fB\-\-setup\fR
Setup by mtfenvset

.TP
\fB\-\-action\fR \fI\,ACTION\/\fR
Action for avocado, see avocado \-\-help for subcommands

.TP
\fB\-\-xunit\fR \fI\,XUNIT\/\fR
Enable xUnit result format and write it to FILE. Use \- to redirect to the standard output.

.TP
\fB\-\-module\fR \fI\,MODULE\/\fR
Module type, like: docker, nspawn or rpm

.TP
\fB\-\-debug\fR
more logging

.TP
\fB\-\-config\fR \fI\,CONFIG\/\fR
defines the module configuration file

.TP
\fB\-\-url\fR \fI\,URL\/\fR
URL overrides the value of module.docker.container or module.rpm.repo.

.TP
\fB\-\-modulemdurl\fR \fI\,MODULEMDURL\/\fR
overwrites the location of a moduleMD file

.SH AUTHORS
.B meta\-test\-family
was written by Jan Scotka <jscotka@redhat.com>.
.SH DISTRIBUTION
The latest version of meta\-test\-family may be downloaded from
.UR https://github.com/fedora\-modularity/meta\-test\-family
.UE
