#!/bin/bash

TESTING="memcached"
TYPES="docker"
for SERVICE in $TESTING; do
    for TYPE in $TYPES; do (
        cd $SERVICE
        MODULE=$TYPE avocado run ./*.py /usr/share/moduleframework/*.py
    )
    done
done
