document: meta-test
version: 1
name: mariadb
testdependencies:
    rpms:
        - nc
        - community-mysql
default_module: docker
module:
    docker:
        start: docker run -p 3306:3306 -e MYSQL_ROOT_PASSWORD={PASSWORD}
        container: docker.io/mariadb
